package presentatie.RelDB;

import java.sql.Time;
import java.util.List;
import logica.DataLayer;
import logica.DayProduction;
import logica.Installation;

/**
 *
 * @author Olivier PC
 */
public class DB_Gui extends javax.swing.JFrame {

    private DataLayer db;
    private List<Installation> allInstallations;
    private Installation installation;
    private DayProduction dayProduction;
    private List<Time> times;
    private List<Double> values;

    /**
     * Creates new form DB_Gui
     */
    public DB_Gui() {
        initComponents();
        this.db = new DataLayer();
        this.allInstallations = db.retrieveAllInstallations();
        this.fillComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOwnerInfo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaProductionInfo = new javax.swing.JTextArea();
        jComboBoxInstallationSelection = new javax.swing.JComboBox<>();
        dB_Graph1 = new presentatie.RelDB.DB_Graph();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextAreaOwnerInfo.setColumns(20);
        jTextAreaOwnerInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOwnerInfo);

        jTextAreaProductionInfo.setColumns(20);
        jTextAreaProductionInfo.setRows(5);
        jScrollPane2.setViewportView(jTextAreaProductionInfo);

        jComboBoxInstallationSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxInstallationSelectionActionPerformed(evt);
            }
        });

        dB_Graph1.setBackground(new java.awt.Color(255, 255, 255));
        dB_Graph1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dB_Graph1.setPreferredSize(new java.awt.Dimension(360, 864));

        javax.swing.GroupLayout dB_Graph1Layout = new javax.swing.GroupLayout(dB_Graph1);
        dB_Graph1.setLayout(dB_Graph1Layout);
        dB_Graph1Layout.setHorizontalGroup(
            dB_Graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        dB_Graph1Layout.setVerticalGroup(
            dB_Graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dB_Graph1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxInstallationSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxInstallationSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dB_Graph1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxInstallationSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxInstallationSelectionActionPerformed
        // TODO add your handling code here:
        int systeemID = this.jComboBoxInstallationSelection.getSelectedIndex() + 1;
        this.installation = this.db.retrieveInstallationDetails(systeemID);
        this.dayProduction = new DayProduction(this.db.setDayProduction(systeemID).toString());
        this.times = this.db.setTimes(systeemID);
        this.values = this.db.setMeasurements(systeemID);
        String[][] combinedValues = this.db.combineTimesAndMeasurements(this.times, this.values);

        this.dayProduction.parseCustomData(combinedValues);
        this.dayProduction.calculateStringOutput();
        this.dB_Graph1.fillMeasurements(values);
        this.jTextAreaOwnerInfo.setText(this.installation.toString());
        this.jTextAreaProductionInfo.setText(this.dayProduction.toString());
    }//GEN-LAST:event_jComboBoxInstallationSelectionActionPerformed

    private void fillComboBox() {
        for (int i = 0; i < this.allInstallations.size(); i++) {
            this.jComboBoxInstallationSelection.insertItemAt(this.allInstallations.get(i).getSysteemID() + ": " + this.allInstallations.get(i).getMerk(), i);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DB_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DB_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DB_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DB_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DB_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentatie.RelDB.DB_Graph dB_Graph1;
    private javax.swing.JComboBox<String> jComboBoxInstallationSelection;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaOwnerInfo;
    private javax.swing.JTextArea jTextAreaProductionInfo;
    // End of variables declaration//GEN-END:variables
}
