package presentatie.JavaOO_dl4;

import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import logica.DayProduction;

/**
 *
 * @author Olivier PC
 */
public class Frame_2Days extends javax.swing.JFrame {

    private DayProduction firstDayProduction;
    private DayProduction secondDayProduction;

    /**
     * Creates new form Frame_1Day
     */
    public Frame_2Days() {
        initComponents();
        LocalDate date = LocalDate.of(2017, 07, 03); // Sets the starting date on 2017-07-03.
        this.firstDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo1);
        this.secondDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate2, this.jTextAreaDayProductionInfo2);
        this.setValuesForPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDate1 = new javax.swing.JLabel();
        jTextFieldDate1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDayProductionInfo1 = new javax.swing.JTextArea();
        jLabelNext1 = new javax.swing.JLabel();
        jLabelLast1 = new javax.swing.JLabel();
        jLabelPrevious1 = new javax.swing.JLabel();
        jLabelFirst1 = new javax.swing.JLabel();
        jLabel_YAxisLeft6 = new javax.swing.JLabel();
        jLabel_YAxisLeft5 = new javax.swing.JLabel();
        jLabel_YAxisLeft4 = new javax.swing.JLabel();
        jLabel_YAxisLeft3 = new javax.swing.JLabel();
        jLabel_YAxisLeft2 = new javax.swing.JLabel();
        jLabel_YAxisLeft1 = new javax.swing.JLabel();
        jLabel_XAxis1 = new javax.swing.JLabel();
        jLabel_XAxis2 = new javax.swing.JLabel();
        jLabel_XAxis3 = new javax.swing.JLabel();
        jLabel_XAxis4 = new javax.swing.JLabel();
        jLabel_XAxis5 = new javax.swing.JLabel();
        jLabel_XAxis6 = new javax.swing.JLabel();
        jLabel_XAxis7 = new javax.swing.JLabel();
        jLabel_XAxis8 = new javax.swing.JLabel();
        jLabel_XAxis9 = new javax.swing.JLabel();
        panel_2Days1 = new presentatie.JavaOO_dl4.Panel_2Days();
        jLabelNext2 = new javax.swing.JLabel();
        jLabelLast2 = new javax.swing.JLabel();
        jLabelPrevious2 = new javax.swing.JLabel();
        jLabelFirst2 = new javax.swing.JLabel();
        jLabelDate2 = new javax.swing.JLabel();
        jTextFieldDate2 = new javax.swing.JTextField();
        jLabel_YAxisRight6 = new javax.swing.JLabel();
        jLabel_YAxisRight5 = new javax.swing.JLabel();
        jLabel_YAxisRight4 = new javax.swing.JLabel();
        jLabel_YAxisRight3 = new javax.swing.JLabel();
        jLabel_YAxisRight2 = new javax.swing.JLabel();
        jLabel_YAxisRight1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDayProductionInfo2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelDate1.setText("Datum:");

        jTextFieldDate1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDate1.setText("2017-07-03");
        jTextFieldDate1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDate1FocusGained(evt);
            }
        });
        jTextFieldDate1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDate1KeyPressed(evt);
            }
        });

        jTextAreaDayProductionInfo1.setColumns(20);
        jTextAreaDayProductionInfo1.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDayProductionInfo1);

        jLabelNext1.setIcon(new ImageIcon("images/next.png"));
        jLabelNext1.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNext1MouseClicked(evt);
            }
        });

        jLabelLast1.setIcon(new ImageIcon("images/last.png"));
        jLabelLast1.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelLast1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLast11MouseClicked(evt);
            }
        });

        jLabelPrevious1.setIcon(new ImageIcon("images/previous.png"));
        jLabelPrevious1.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelPrevious1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPrevious1MouseClicked(evt);
            }
        });

        jLabelFirst1.setIcon(new ImageIcon("images/first.png"));
        jLabelFirst1.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelFirst1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFirst1MouseClicked(evt);
            }
        });

        jLabel_YAxisLeft6.setText("5.0");

        jLabel_YAxisLeft5.setText("4.0");

        jLabel_YAxisLeft4.setText("3.0");

        jLabel_YAxisLeft3.setText("2.0");

        jLabel_YAxisLeft2.setText("1.0");

        jLabel_YAxisLeft1.setText("0.0");

        jLabel_XAxis1.setText("00:00");

        jLabel_XAxis2.setText("03:00");

        jLabel_XAxis3.setText("06:00");

        jLabel_XAxis4.setText("09:00");

        jLabel_XAxis5.setText("12:00");

        jLabel_XAxis6.setText("15:00");

        jLabel_XAxis7.setText("18:00");

        jLabel_XAxis8.setText("21:00");

        jLabel_XAxis9.setText("24:00");

        panel_2Days1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_2Days1Layout = new javax.swing.GroupLayout(panel_2Days1);
        panel_2Days1.setLayout(panel_2Days1Layout);
        panel_2Days1Layout.setHorizontalGroup(
            panel_2Days1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        panel_2Days1Layout.setVerticalGroup(
            panel_2Days1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jLabelNext2.setIcon(new ImageIcon("images/next.png"));
        jLabelNext2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelNext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNext2MouseClicked(evt);
            }
        });

        jLabelLast2.setIcon(new ImageIcon("images/last.png"));
        jLabelLast2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelLast2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLast2MouseClicked(evt);
            }
        });

        jLabelPrevious2.setIcon(new ImageIcon("images/previous.png"));
        jLabelPrevious2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelPrevious2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPrevious2MouseClicked(evt);
            }
        });

        jLabelFirst2.setIcon(new ImageIcon("images/first.png"));
        jLabelFirst2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelFirst2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFirst2MouseClicked(evt);
            }
        });

        jLabelDate2.setText("Datum:");

        jTextFieldDate2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDate2.setText("2017-07-03");
        jTextFieldDate2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDate2FocusGained(evt);
            }
        });
        jTextFieldDate2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDate2KeyPressed(evt);
            }
        });

        jLabel_YAxisRight6.setText("5.0");

        jLabel_YAxisRight5.setText("4.0");

        jLabel_YAxisRight4.setText("3.0");

        jLabel_YAxisRight3.setText("2.0");

        jLabel_YAxisRight2.setText("1.0");

        jLabel_YAxisRight1.setText("0.0");

        jTextAreaDayProductionInfo2.setColumns(20);
        jTextAreaDayProductionInfo2.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDayProductionInfo2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabelDate1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLast1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabelDate2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFirst2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrevious2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLast2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_YAxisLeft6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxisLeft5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxisLeft4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxisLeft3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxisLeft2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxisLeft1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_XAxis1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_XAxis2)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel_XAxis3)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel_XAxis4)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel_XAxis5)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel_XAxis6)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel_XAxis7)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel_XAxis8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_XAxis9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_2Days1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_YAxisRight6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_YAxisRight5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_YAxisRight4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_YAxisRight3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_YAxisRight2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel_YAxisRight1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDate2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFirst2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrevious2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLast2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLast1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_YAxisLeft6)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_YAxisLeft5)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel_YAxisLeft4)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_YAxisLeft3)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_YAxisLeft2)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_YAxisLeft1))
                    .addComponent(panel_2Days1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_YAxisRight6)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_YAxisRight5)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel_YAxisRight4)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_YAxisRight3)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_YAxisRight2)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_YAxisRight1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_XAxis1)
                    .addComponent(jLabel_XAxis2)
                    .addComponent(jLabel_XAxis3)
                    .addComponent(jLabel_XAxis4)
                    .addComponent(jLabel_XAxis5)
                    .addComponent(jLabel_XAxis6)
                    .addComponent(jLabel_XAxis7)
                    .addComponent(jLabel_XAxis8)
                    .addComponent(jLabel_XAxis9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDate1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDate1FocusGained
        // TODO add your handling code here:
        this.jTextFieldDate1.selectAll();
    }//GEN-LAST:event_jTextFieldDate1FocusGained

    private void jLabelNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNext1MouseClicked
        // TODO add your handling code here:
        if (this.firstDayProduction.getDate().isBefore(LocalDate.of(2018, 04, 30))) {
            this.firstDayProduction.setDate(this.firstDayProduction.getDate().plusDays(1));
            this.jTextFieldDate1.setText(this.firstDayProduction.getDate().toString());
            this.firstDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo1);
            this.setValuesForPanel();
        }
    }//GEN-LAST:event_jLabelNext1MouseClicked

    private void jLabelLast11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLast11MouseClicked
        // TODO add your handling code here:
        this.firstDayProduction.setDate(LocalDate.of(2018, 04, 30));
        this.jTextFieldDate1.setText(this.firstDayProduction.getDate().toString());
        this.firstDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo1);
        this.setValuesForPanel();
    }//GEN-LAST:event_jLabelLast11MouseClicked

    private void jLabelPrevious1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrevious1MouseClicked
        // TODO add your handling code here:
        if (this.firstDayProduction.getDate().isAfter(LocalDate.of(2017, 07, 03))) {
            this.firstDayProduction.setDate(this.firstDayProduction.getDate().minusDays(1));
            this.jTextFieldDate1.setText(this.firstDayProduction.getDate().toString());
            this.firstDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo1);
            this.setValuesForPanel();
        }
    }//GEN-LAST:event_jLabelPrevious1MouseClicked

    private void jLabelFirst1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFirst1MouseClicked
        // TODO add your handling code here:
        this.firstDayProduction.setDate(LocalDate.of(2017, 07, 03));
        this.jTextFieldDate1.setText(this.firstDayProduction.getDate().toString());
        this.firstDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo1);
        this.setValuesForPanel();
    }//GEN-LAST:event_jLabelFirst1MouseClicked

    private void jTextFieldDate1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDate1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.firstDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo1);
            this.setValuesForPanel();
        }
    }//GEN-LAST:event_jTextFieldDate1KeyPressed

    private void jLabelNext2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNext2MouseClicked
        // TODO add your handling code here:
        if (this.secondDayProduction.getDate().isBefore(LocalDate.of(2018, 04, 30))) {
            this.secondDayProduction.setDate(this.secondDayProduction.getDate().plusDays(1));
            this.jTextFieldDate2.setText(this.secondDayProduction.getDate().toString());
            this.secondDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate2, this.jTextAreaDayProductionInfo2);
            this.setValuesForPanel();
        }
    }//GEN-LAST:event_jLabelNext2MouseClicked

    private void jLabelLast2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLast2MouseClicked
        // TODO add your handling code here:
        this.secondDayProduction.setDate(LocalDate.of(2018, 04, 30));
        this.jTextFieldDate2.setText(this.secondDayProduction.getDate().toString());
        this.secondDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate2, this.jTextAreaDayProductionInfo2);
        this.setValuesForPanel();
    }//GEN-LAST:event_jLabelLast2MouseClicked

    private void jLabelPrevious2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrevious2MouseClicked
        // TODO add your handling code here:
        if (this.secondDayProduction.getDate().isAfter(LocalDate.of(2017, 07, 03))) {
            this.secondDayProduction.setDate(this.secondDayProduction.getDate().minusDays(1));
            this.jTextFieldDate2.setText(this.secondDayProduction.getDate().toString());
            this.secondDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate2, this.jTextAreaDayProductionInfo2);
            this.setValuesForPanel();
        }
    }//GEN-LAST:event_jLabelPrevious2MouseClicked

    private void jLabelFirst2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFirst2MouseClicked
        // TODO add your handling code here:
        this.secondDayProduction.setDate(LocalDate.of(2017, 07, 03));
        this.jTextFieldDate2.setText(this.secondDayProduction.getDate().toString());
        this.secondDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate2, this.jTextAreaDayProductionInfo2);
        this.setValuesForPanel();
    }//GEN-LAST:event_jLabelFirst2MouseClicked

    private void jTextFieldDate2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDate2FocusGained
        // TODO add your handling code here:
        this.jTextFieldDate2.selectAll();
    }//GEN-LAST:event_jTextFieldDate2FocusGained

    private void jTextFieldDate2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDate2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.secondDayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate2, this.jTextAreaDayProductionInfo2);
            this.setValuesForPanel();
        }
    }//GEN-LAST:event_jTextFieldDate2KeyPressed

    /**
     * Makes a temporary DayProduction object based on what the input of the
     * given textField is, and display the information on the given textArea.
     *
     * @param textField textField from which the date is extracted.
     * @param textArea textArea in which the DayProduction toString will be
     * shown.
     * @return a DayProduction object filled with custom data, based on what
     * date was passed in the textField.
     */
    private DayProduction createAndDisplayDayProduction(JTextField textField, JTextArea textArea) {
        DayProduction tempDayProduction = new DayProduction(textField.getText());
        tempDayProduction.setCustomData();
        textArea.setText(tempDayProduction.toString());
        return tempDayProduction;
    }

    private void setValuesForPanel() {
        this.panel_2Days1.fillMeasurements(this.firstDayProduction.fillCustomData(), this.secondDayProduction.fillCustomData());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_2Days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_2Days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_2Days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_2Days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_2Days().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDate1;
    private javax.swing.JLabel jLabelDate2;
    private javax.swing.JLabel jLabelFirst1;
    private javax.swing.JLabel jLabelFirst2;
    private javax.swing.JLabel jLabelLast1;
    private javax.swing.JLabel jLabelLast2;
    private javax.swing.JLabel jLabelNext1;
    private javax.swing.JLabel jLabelNext2;
    private javax.swing.JLabel jLabelPrevious1;
    private javax.swing.JLabel jLabelPrevious2;
    private javax.swing.JLabel jLabel_XAxis1;
    private javax.swing.JLabel jLabel_XAxis2;
    private javax.swing.JLabel jLabel_XAxis3;
    private javax.swing.JLabel jLabel_XAxis4;
    private javax.swing.JLabel jLabel_XAxis5;
    private javax.swing.JLabel jLabel_XAxis6;
    private javax.swing.JLabel jLabel_XAxis7;
    private javax.swing.JLabel jLabel_XAxis8;
    private javax.swing.JLabel jLabel_XAxis9;
    private javax.swing.JLabel jLabel_YAxisLeft1;
    private javax.swing.JLabel jLabel_YAxisLeft2;
    private javax.swing.JLabel jLabel_YAxisLeft3;
    private javax.swing.JLabel jLabel_YAxisLeft4;
    private javax.swing.JLabel jLabel_YAxisLeft5;
    private javax.swing.JLabel jLabel_YAxisLeft6;
    private javax.swing.JLabel jLabel_YAxisRight1;
    private javax.swing.JLabel jLabel_YAxisRight2;
    private javax.swing.JLabel jLabel_YAxisRight3;
    private javax.swing.JLabel jLabel_YAxisRight4;
    private javax.swing.JLabel jLabel_YAxisRight5;
    private javax.swing.JLabel jLabel_YAxisRight6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDayProductionInfo1;
    private javax.swing.JTextArea jTextAreaDayProductionInfo2;
    private javax.swing.JTextField jTextFieldDate1;
    private javax.swing.JTextField jTextFieldDate2;
    private presentatie.JavaOO_dl4.Panel_2Days panel_2Days1;
    // End of variables declaration//GEN-END:variables
}
