package presentatie.JavaOO_dl4;

import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import logica.DayProduction;

/**
 *
 * @author Olivier PC
 */
public class Frame_2Days extends javax.swing.JFrame {

    private DayProduction dayProduction;

    /**
     * Creates new form Frame_1Day
     */
    public Frame_2Days() {
        initComponents();
        LocalDate date = LocalDate.of(2017, 07, 03); // Sets the starting date on 2017-07-03.
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo);
        this.panel_2Days1.fillMeasurements(this.dayProduction.fillCustomData());
        System.out.println(this.panel_2Days1.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDate1 = new javax.swing.JLabel();
        jTextFieldDate1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDayProductionInfo = new javax.swing.JTextArea();
        jLabelNext1 = new javax.swing.JLabel();
        jLabelLast1 = new javax.swing.JLabel();
        jLabelPrevious1 = new javax.swing.JLabel();
        jLabelFirst1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panel_2Days1 = new presentatie.JavaOO_dl4.Panel_2Days();
        jLabelNext2 = new javax.swing.JLabel();
        jLabelLast2 = new javax.swing.JLabel();
        jLabelPrevious2 = new javax.swing.JLabel();
        jLabelFirst2 = new javax.swing.JLabel();
        jLabelDate2 = new javax.swing.JLabel();
        jTextFieldDate2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelDate1.setText("Datum:");

        jTextFieldDate1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDate1.setText("2017-07-03");
        jTextFieldDate1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDate1FocusGained(evt);
            }
        });
        jTextFieldDate1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDate1KeyPressed(evt);
            }
        });

        jTextAreaDayProductionInfo.setColumns(20);
        jTextAreaDayProductionInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDayProductionInfo);

        jLabelNext1.setIcon(new ImageIcon("images/next.PNG"));
        jLabelNext1.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNext1MouseClicked(evt);
            }
        });

        jLabelLast1.setIcon(new ImageIcon("images/last.PNG"));
        jLabelLast1.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelLast1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLast1MouseClicked(evt);
            }
        });

        jLabelPrevious1.setIcon(new ImageIcon("images/previous.PNG"));
        jLabelPrevious1.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelPrevious1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPrevious1MouseClicked(evt);
            }
        });

        jLabelFirst1.setIcon(new ImageIcon("images/first.PNG"));
        jLabelFirst1.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelFirst1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFirst1MouseClicked(evt);
            }
        });

        jLabel1.setText("5.0");

        jLabel2.setText("4.0");

        jLabel3.setText("3.0");

        jLabel4.setText("2.0");

        jLabel5.setText("1.0");

        jLabel7.setText("0.0");

        jLabel6.setText("00:00");

        jLabel8.setText("03:00");

        jLabel9.setText("06:00");

        jLabel10.setText("09:00");

        jLabel11.setText("12:00");

        jLabel12.setText("15:00");

        jLabel13.setText("18:00");

        jLabel14.setText("21:00");

        jLabel15.setText("24:00");

        panel_2Days1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout panel_2Days1Layout = new javax.swing.GroupLayout(panel_2Days1);
        panel_2Days1.setLayout(panel_2Days1Layout);
        panel_2Days1Layout.setHorizontalGroup(
            panel_2Days1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        panel_2Days1Layout.setVerticalGroup(
            panel_2Days1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jLabelNext2.setIcon(new ImageIcon("images/next.PNG"));
        jLabelNext2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelNext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNext2MouseClicked(evt);
            }
        });

        jLabelLast2.setIcon(new ImageIcon("images/last.PNG"));
        jLabelLast2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelLast2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLast2MouseClicked(evt);
            }
        });

        jLabelPrevious2.setIcon(new ImageIcon("images/previous.PNG"));
        jLabelPrevious2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelPrevious2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPrevious2MouseClicked(evt);
            }
        });

        jLabelFirst2.setIcon(new ImageIcon("images/first.PNG"));
        jLabelFirst2.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelFirst2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFirst2MouseClicked(evt);
            }
        });

        jLabelDate2.setText("Datum:");

        jTextFieldDate2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDate2.setText("2017-07-03");
        jTextFieldDate2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDate2FocusGained(evt);
            }
        });
        jTextFieldDate2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDate2KeyPressed(evt);
            }
        });

        jLabel16.setText("5.0");

        jLabel17.setText("4.0");

        jLabel18.setText("3.0");

        jLabel19.setText("2.0");

        jLabel20.setText("1.0");

        jLabel21.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel13)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_2Days1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabelDate1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLast1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabelDate2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFirst2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrevious2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLast2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDate2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFirst2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNext2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDate2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrevious2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLast2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrevious1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLast1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7))
                    .addComponent(panel_2Days1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel17)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel18)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel19)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel20)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDate1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDate1FocusGained
        // TODO add your handling code here:
        this.jTextFieldDate1.selectAll();
    }//GEN-LAST:event_jTextFieldDate1FocusGained

    private void jLabelNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNext1MouseClicked
        // TODO add your handling code here:
        if (this.dayProduction.getDate().isBefore(LocalDate.of(2018, 04, 30))) {
            this.dayProduction.setDate(this.dayProduction.getDate().plusDays(1));
            this.jTextFieldDate1.setText(this.dayProduction.getDate().toString());
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo);
            this.panel_2Days1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jLabelNext1MouseClicked

    private void jLabelLast1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLast1MouseClicked
        // TODO add your handling code here:
        this.dayProduction.setDate(LocalDate.of(2018, 04, 30));
        this.jTextFieldDate1.setText(this.dayProduction.getDate().toString());
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo);
        this.panel_2Days1.fillMeasurements(this.dayProduction.fillCustomData());
    }//GEN-LAST:event_jLabelLast1MouseClicked

    private void jLabelPrevious1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrevious1MouseClicked
        // TODO add your handling code here:
        if (this.dayProduction.getDate().isAfter(LocalDate.of(2017, 07, 03))) {
            this.dayProduction.setDate(this.dayProduction.getDate().minusDays(1));
            this.jTextFieldDate1.setText(this.dayProduction.getDate().toString());
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo);
            this.panel_2Days1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jLabelPrevious1MouseClicked

    private void jLabelFirst1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFirst1MouseClicked
        // TODO add your handling code here:
        this.dayProduction.setDate(LocalDate.of(2017, 07, 03));
        this.jTextFieldDate1.setText(this.dayProduction.getDate().toString());
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo);
        this.panel_2Days1.fillMeasurements(this.dayProduction.fillCustomData());
    }//GEN-LAST:event_jLabelFirst1MouseClicked

    private void jTextFieldDate1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDate1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate1, this.jTextAreaDayProductionInfo);
            this.panel_2Days1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jTextFieldDate1KeyPressed

    private void jLabelNext2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNext2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNext2MouseClicked

    private void jLabelLast2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLast2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelLast2MouseClicked

    private void jLabelPrevious2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPrevious2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPrevious2MouseClicked

    private void jLabelFirst2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFirst2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFirst2MouseClicked

    private void jTextFieldDate2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDate2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDate2FocusGained

    private void jTextFieldDate2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDate2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDate2KeyPressed

    /**
     * Makes a temporary DayProduction object based on what the input of the
     * given textField is, and display the information on the given textArea.
     *
     * @param textField textField from which the date is extracted.
     * @param textArea textArea in which the DayProduction toString will be
     * shown.
     * @return a DayProduction object filled with custom data, based on what
     * date was passed in the textField.
     */
    private DayProduction createAndDisplayDayProduction(JTextField textField, JTextArea textArea) {
        DayProduction tempDayProduction = new DayProduction(textField.getText());
        tempDayProduction.setCustomData();
        textArea.setText(tempDayProduction.toString());
        return tempDayProduction;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_2Days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_2Days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_2Days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_2Days.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_2Days().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDate1;
    private javax.swing.JLabel jLabelDate2;
    private javax.swing.JLabel jLabelFirst1;
    private javax.swing.JLabel jLabelFirst2;
    private javax.swing.JLabel jLabelLast1;
    private javax.swing.JLabel jLabelLast2;
    private javax.swing.JLabel jLabelNext1;
    private javax.swing.JLabel jLabelNext2;
    private javax.swing.JLabel jLabelPrevious1;
    private javax.swing.JLabel jLabelPrevious2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDayProductionInfo;
    private javax.swing.JTextField jTextFieldDate1;
    private javax.swing.JTextField jTextFieldDate2;
    private presentatie.JavaOO_dl4.Panel_2Days panel_2Days1;
    // End of variables declaration//GEN-END:variables
}
