package presentatie.JavaOO_dl4;

import presentatie.JavaOO_dl3.*;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author Olivier PC
 */
public class Panel_2Days extends javax.swing.JPanel {

    private ArrayList<Double> firstMeasurements;
    private ArrayList<Double> secondMeasurements;
    private Graphics g;
    private int width;
    private int height;

    /**
     * Creates new form Panel_2Days
     */
    public Panel_2Days() {
        initComponents();
        this.setBorder(BorderFactory.createLineBorder(Color.black));
        this.firstMeasurements = new ArrayList<>();
        this.secondMeasurements = new ArrayList<>();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        this.g = g;
        this.g.setColor(Color.BLACK);
        this.drawAxis();
        this.drawGraph();
        this.repaint();
    }

    private void drawGraph() {
        if (!this.firstMeasurements.isEmpty() && !this.secondMeasurements.isEmpty()) {

            this.width = this.getWidth();
            this.height = this.getHeight();

            for (int i = 0; i < this.firstMeasurements.size(); i++) { // for loop going over all the measurements of the first object and plotting them on the graph.
                this.g.drawOval(i * 5, this.height - 2 - (int) (this.height * this.firstMeasurements.get(i) / 5), 4, 4);
                if (i >= 1) {
                    int firstX = i * 5 - 3;
                    int secondX = i * 5 + 2;
                    int firstY = this.height - (int) (this.height * this.firstMeasurements.get(i - 1) / 5);
                    int secondY = this.height - (int) (this.height * this.firstMeasurements.get(i) / 5);
                    this.g.drawLine(firstX, firstY, secondX, secondY);
                }
            }
            this.g.setColor(Color.RED);
            for (int i = 0; i < this.secondMeasurements.size(); i++) { // for loop going over all the measurements of the second object and plotting them on the graph.
                this.g.drawOval(i * 5, this.height - 2 - (int) (this.height * this.secondMeasurements.get(i) / 5), 4, 4);
                if (i >= 1) {
                    int firstX = i * 5 - 3;
                    int secondX = i * 5 + 2;
                    int firstY = this.height - (int) (this.height * this.secondMeasurements.get(i - 1) / 5);
                    int secondY = this.height - (int) (this.height * this.secondMeasurements.get(i) / 5);
                    this.g.drawLine(firstX, firstY, secondX, secondY);
                }
            }
            this.repaint();
        }
    }

    private void drawAxis() {
        if (!this.firstMeasurements.isEmpty() && !this.secondMeasurements.isEmpty()) {
            for (int i = 0; i <= this.width; i += 60) {
                this.g.drawLine(i, 0, i, this.height);
            }
            for (int i = 0; i <= this.height; i += 60) {
                this.g.drawLine(0, i, this.width, i);
            }
        }
    }

    /**
     * Fills an ArrayList with only the measurements of a certain day, excluding
     * the times. If there is no value, a 0.0 will be added.
     *
     * @param arr1 String[][] filled with times and their measurement of the
     * first DayProduction.
     * @param arr1 String[][] filled with times and their measurement of the
     * second DayProduction.
     */
    protected void fillMeasurements(String[][] arr1, String[][] arr2) {

        this.firstMeasurements = new ArrayList<>();
        this.secondMeasurements = new ArrayList<>();

        for (int i = 0; i < arr1.length; i++) {
            if (arr1[i].length >= 2 && Double.parseDouble(arr1[i][1]) > 0) {
                double measurement = Double.parseDouble(arr1[i][1]);
                this.firstMeasurements.add(measurement);
            } else {
                this.firstMeasurements.add(0.0);
            }
        }
        for (int i = 0; i < arr2.length; i++) {
            if (arr2[i].length >= 2 && Double.parseDouble(arr2[i][1]) > 0) {
                double measurement = Double.parseDouble(arr2[i][1]);
                this.secondMeasurements.add(measurement);
            } else {
                this.secondMeasurements.add(0.0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(480, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
