package presentatie.JavaOO_dl2;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author Olivier PC
 */
public class Panel_1Day extends javax.swing.JPanel {

    private ArrayList<Double> measurements;
    private Graphics g;

    /**
     * Creates new form Panel_1Day
     */
    public Panel_1Day() {
        initComponents();
        this.measurements = new ArrayList<>();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        this.g = g;
        this.g.setColor(Color.BLACK);
        this.drawGraph();
        this.repaint();
    }

    private void drawGraph() {
        if (!this.measurements.isEmpty()) {
            int width = this.getWidth();
            int height = this.getHeight();
            for (int i = 0; i < this.measurements.size(); i++) { // for loop going over all the measurements and plotting them on the graph.
                g.drawOval(i * 5, height - 2 - (int) (height * this.measurements.get(i) / 4), 4, 4);
                if (i >= 1) {
                    int firstX = i * 5 - 3;
                    int secondX = i * 5 + 2;
                    int firstY = height - (int) (height * this.measurements.get(i - 1) / 4);
                    int secondY = height - (int) (height * this.measurements.get(i) / 4);
                    g.drawLine(firstX, firstY, secondX, secondY);
                }
            }
            this.repaint();
        }
    }

    /**
     * Fills an ArrayList with only the measurements of a certain day, excluding
     * the times. If there is no value, a 0.0 will be added.
     *
     * @param arr String[][] filled with times and their measurement.
     */
    protected void fillMeasurements(String[][] arr) {
        this.measurements = new ArrayList<>();
        for (int i = 0; i < arr.length; i++) {
            if (arr[i].length >= 2 && Double.parseDouble(arr[i][1]) > 0) {
                double measurement = Double.parseDouble(arr[i][1]);
                this.measurements.add(measurement);
            } else {
                this.measurements.add(0.0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(480, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
