package presentatie.JavaOO_dl3;

import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import logica.DayProduction;
import presentatie.JavaOO_dl3.Panel_navigation;

/**
 *
 * @author Olivier PC
 */
public class Frame_navigation extends javax.swing.JFrame {

    private DayProduction dayProduction;

    /**
     * Creates new form Frame_1Day
     */
    public Frame_navigation() {
        initComponents();
        LocalDate date = LocalDate.of(2017, 07, 03); // Sets the starting date on 2017-07-03.
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        System.out.println(this.panel_navigation1.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDate = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDayProductionInfo = new javax.swing.JTextArea();
        jLabelNext = new javax.swing.JLabel();
        jLabelLast = new javax.swing.JLabel();
        jLabelPrevious = new javax.swing.JLabel();
        jLabelFirst = new javax.swing.JLabel();
        panel_navigation1 = new presentatie.JavaOO_dl3.Panel_navigation();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelDate.setText("Datum:");

        jTextFieldDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDate.setText("2017-07-03");
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
        });
        jTextFieldDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDateKeyPressed(evt);
            }
        });

        jTextAreaDayProductionInfo.setColumns(20);
        jTextAreaDayProductionInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDayProductionInfo);

        jLabelNext.setIcon(new ImageIcon("images/next.PNG"));
        jLabelNext.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNextMouseClicked(evt);
            }
        });

        jLabelLast.setIcon(new ImageIcon("images/last.PNG"));
        jLabelLast.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLastMouseClicked(evt);
            }
        });

        jLabelPrevious.setIcon(new ImageIcon("images/previous.PNG"));
        jLabelPrevious.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPreviousMouseClicked(evt);
            }
        });

        jLabelFirst.setIcon(new ImageIcon("images/first.PNG"));
        jLabelFirst.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFirstMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_navigation1Layout = new javax.swing.GroupLayout(panel_navigation1);
        panel_navigation1.setLayout(panel_navigation1Layout);
        panel_navigation1Layout.setHorizontalGroup(
            panel_navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        panel_navigation1Layout.setVerticalGroup(
            panel_navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jLabel1.setText("4.0");

        jLabel2.setText("3.2");

        jLabel3.setText("2.4");

        jLabel4.setText("1.6");

        jLabel5.setText("0.8");

        jLabel7.setText("0.0");

        jLabel6.setText("00:00");

        jLabel8.setText("03:00");

        jLabel9.setText("06:00");

        jLabel10.setText("09:00");

        jLabel11.setText("12:00");

        jLabel12.setText("15:00");

        jLabel13.setText("18:00");

        jLabel14.setText("21:00");

        jLabel15.setText("24:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabelDate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel13)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addComponent(panel_navigation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7))
                    .addComponent(panel_navigation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        // TODO add your handling code here:
        this.jTextFieldDate.selectAll();
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jLabelNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNextMouseClicked
        // TODO add your handling code here:
        if (this.dayProduction.getDate().isBefore(LocalDate.of(2018, 04, 30))) {
            this.dayProduction.setDate(this.dayProduction.getDate().plusDays(1));
            this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jLabelNextMouseClicked

    private void jLabelLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLastMouseClicked
        // TODO add your handling code here:
        this.dayProduction.setDate(LocalDate.of(2018, 04, 30));
        this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
    }//GEN-LAST:event_jLabelLastMouseClicked

    private void jLabelPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPreviousMouseClicked
        // TODO add your handling code here:
        if (this.dayProduction.getDate().isAfter(LocalDate.of(2017, 07, 03))) {
            this.dayProduction.setDate(this.dayProduction.getDate().minusDays(1));
            this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jLabelPreviousMouseClicked

    private void jLabelFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFirstMouseClicked
        // TODO add your handling code here:
        this.dayProduction.setDate(LocalDate.of(2017, 07, 03));
        this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
    }//GEN-LAST:event_jLabelFirstMouseClicked

    private void jTextFieldDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jTextFieldDateKeyPressed

    /**
     * Makes a temporary DayProduction object based on what the input of the
     * given textField is, and display the information on the given textArea.
     *
     * @param textField textField from which the date is extracted.
     * @param textArea textArea in which the DayProduction toString will be
     * shown.
     * @return a DayProduction object filled with custom data, based on what
     * date was passed in the textField.
     */
    private DayProduction createAndDisplayDayProduction(JTextField textField, JTextArea textArea) {
        DayProduction tempDayProduction = new DayProduction(textField.getText());
        tempDayProduction.setCustomData();
        textArea.setText(tempDayProduction.toString());
        return tempDayProduction;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_navigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelFirst;
    private javax.swing.JLabel jLabelLast;
    private javax.swing.JLabel jLabelNext;
    private javax.swing.JLabel jLabelPrevious;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDayProductionInfo;
    private javax.swing.JTextField jTextFieldDate;
    private presentatie.JavaOO_dl3.Panel_navigation panel_navigation1;
    // End of variables declaration//GEN-END:variables
}
