package presentatie.JavaOO_dl3;

import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import logica.DayProduction;

/**
 *
 * @author Olivier PC
 */
public class Frame_navigation extends javax.swing.JFrame {

    private DayProduction dayProduction;

    /**
     * Creates new form Frame_1Day
     */
    public Frame_navigation() {
        initComponents();
        LocalDate date = LocalDate.of(2017, 07, 03); // Sets the starting date on 2017-07-03.
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        System.out.println(this.panel_navigation1.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDate = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDayProductionInfo = new javax.swing.JTextArea();
        jLabelNext = new javax.swing.JLabel();
        jLabelLast = new javax.swing.JLabel();
        jLabelPrevious = new javax.swing.JLabel();
        jLabelFirst = new javax.swing.JLabel();
        panel_navigation1 = new presentatie.JavaOO_dl3.Panel_navigation();
        jLabel_YAxis6 = new javax.swing.JLabel();
        jLabel_YAxis5 = new javax.swing.JLabel();
        jLabel_YAxis4 = new javax.swing.JLabel();
        jLabel_YAxis3 = new javax.swing.JLabel();
        jLabel_YAxis2 = new javax.swing.JLabel();
        jLabel_YAxis1 = new javax.swing.JLabel();
        jLabel_XAxis1 = new javax.swing.JLabel();
        jLabel_XAxis2 = new javax.swing.JLabel();
        jLabel_XAxis3 = new javax.swing.JLabel();
        jLabel_XAxis4 = new javax.swing.JLabel();
        jLabel_XAxis5 = new javax.swing.JLabel();
        jLabel_XAxis6 = new javax.swing.JLabel();
        jLabel_XAxis7 = new javax.swing.JLabel();
        jLabel_XAxis8 = new javax.swing.JLabel();
        jLabel_XAxis9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelDate.setText("Datum:");

        jTextFieldDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDate.setText("2017-07-03");
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
        });
        jTextFieldDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDateKeyPressed(evt);
            }
        });

        jTextAreaDayProductionInfo.setColumns(20);
        jTextAreaDayProductionInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDayProductionInfo);

        jLabelNext.setIcon(new ImageIcon("images/next.png"));
        jLabelNext.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNextMouseClicked(evt);
            }
        });

        jLabelLast.setIcon(new ImageIcon("images/last.png"));
        jLabelLast.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLastMouseClicked(evt);
            }
        });

        jLabelPrevious.setIcon(new ImageIcon("images/previous.png"));
        jLabelPrevious.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPreviousMouseClicked(evt);
            }
        });

        jLabelFirst.setIcon(new ImageIcon("images/first.png"));
        jLabelFirst.setPreferredSize(new java.awt.Dimension(25, 25));
        jLabelFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFirstMouseClicked(evt);
            }
        });

        panel_navigation1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel_navigation1Layout = new javax.swing.GroupLayout(panel_navigation1);
        panel_navigation1.setLayout(panel_navigation1Layout);
        panel_navigation1Layout.setHorizontalGroup(
            panel_navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        panel_navigation1Layout.setVerticalGroup(
            panel_navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jLabel_YAxis6.setText("4.0");

        jLabel_YAxis5.setText("3.2");

        jLabel_YAxis4.setText("2.4");

        jLabel_YAxis3.setText("1.6");

        jLabel_YAxis2.setText("0.8");

        jLabel_YAxis1.setText("0.0");

        jLabel_XAxis1.setText("00:00");

        jLabel_XAxis2.setText("03:00");

        jLabel_XAxis3.setText("06:00");

        jLabel_XAxis4.setText("09:00");

        jLabel_XAxis5.setText("12:00");

        jLabel_XAxis6.setText("15:00");

        jLabel_XAxis7.setText("18:00");

        jLabel_XAxis8.setText("21:00");

        jLabel_XAxis9.setText("24:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabelDate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_YAxis6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxis5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxis4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxis3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxis2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_YAxis1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_XAxis1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_XAxis2)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel_XAxis3)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel_XAxis4)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel_XAxis5)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel_XAxis6)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel_XAxis7)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel_XAxis8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_XAxis9))
                            .addComponent(panel_navigation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_YAxis6)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_YAxis5)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel_YAxis4)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel_YAxis3)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_YAxis2)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel_YAxis1))
                    .addComponent(panel_navigation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_XAxis1)
                    .addComponent(jLabel_XAxis2)
                    .addComponent(jLabel_XAxis3)
                    .addComponent(jLabel_XAxis4)
                    .addComponent(jLabel_XAxis5)
                    .addComponent(jLabel_XAxis6)
                    .addComponent(jLabel_XAxis7)
                    .addComponent(jLabel_XAxis8)
                    .addComponent(jLabel_XAxis9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        // TODO add your handling code here:
        this.jTextFieldDate.selectAll();
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jLabelNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNextMouseClicked
        // TODO add your handling code here:
        if (this.dayProduction.getDate().isBefore(LocalDate.of(2018, 04, 30))) {
            this.dayProduction.setDate(this.dayProduction.getDate().plusDays(1));
            this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jLabelNextMouseClicked

    private void jLabelLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLastMouseClicked
        // TODO add your handling code here:
        this.dayProduction.setDate(LocalDate.of(2018, 04, 30));
        this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
    }//GEN-LAST:event_jLabelLastMouseClicked

    private void jLabelPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPreviousMouseClicked
        // TODO add your handling code here:
        if (this.dayProduction.getDate().isAfter(LocalDate.of(2017, 07, 03))) {
            this.dayProduction.setDate(this.dayProduction.getDate().minusDays(1));
            this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jLabelPreviousMouseClicked

    private void jLabelFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFirstMouseClicked
        // TODO add your handling code here:
        this.dayProduction.setDate(LocalDate.of(2017, 07, 03));
        this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
    }//GEN-LAST:event_jLabelFirstMouseClicked

    private void jTextFieldDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jTextFieldDateKeyPressed

    /**
     * Makes a temporary DayProduction object based on what the input of the
     * given textField is, and display the information on the given textArea.
     *
     * @param textField textField from which the date is extracted.
     * @param textArea textArea in which the DayProduction toString will be
     * shown.
     * @return a DayProduction object filled with custom data, based on what
     * date was passed in the textField.
     */
    private DayProduction createAndDisplayDayProduction(JTextField textField, JTextArea textArea) {
        DayProduction tempDayProduction = new DayProduction(textField.getText());
        tempDayProduction.setCustomData();
        textArea.setText(tempDayProduction.toString());
        return tempDayProduction;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_navigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelFirst;
    private javax.swing.JLabel jLabelLast;
    private javax.swing.JLabel jLabelNext;
    private javax.swing.JLabel jLabelPrevious;
    private javax.swing.JLabel jLabel_XAxis1;
    private javax.swing.JLabel jLabel_XAxis2;
    private javax.swing.JLabel jLabel_XAxis3;
    private javax.swing.JLabel jLabel_XAxis4;
    private javax.swing.JLabel jLabel_XAxis5;
    private javax.swing.JLabel jLabel_XAxis6;
    private javax.swing.JLabel jLabel_XAxis7;
    private javax.swing.JLabel jLabel_XAxis8;
    private javax.swing.JLabel jLabel_XAxis9;
    private javax.swing.JLabel jLabel_YAxis1;
    private javax.swing.JLabel jLabel_YAxis2;
    private javax.swing.JLabel jLabel_YAxis3;
    private javax.swing.JLabel jLabel_YAxis4;
    private javax.swing.JLabel jLabel_YAxis5;
    private javax.swing.JLabel jLabel_YAxis6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDayProductionInfo;
    private javax.swing.JTextField jTextFieldDate;
    private presentatie.JavaOO_dl3.Panel_navigation panel_navigation1;
    // End of variables declaration//GEN-END:variables
}
