package presentatie.JavaOO_dl3;

import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import logica.DayProduction;
import presentatie.JavaOO_dl3.Panel_navigation;

/**
 *
 * @author Olivier PC
 */
public class Frame_navigation extends javax.swing.JFrame {

    private DayProduction dayProduction;

    /**
     * Creates new form Frame_1Day
     */
    public Frame_navigation() {
        initComponents();
        LocalDate date = LocalDate.of(2017, 07, 03); // Sets the starting date on 2017-07-03.
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        System.out.println(this.panel_navigation1.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDate = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDayProductionInfo = new javax.swing.JTextArea();
        jLabelNext = new javax.swing.JLabel();
        jLabelLast = new javax.swing.JLabel();
        jLabelPrevious = new javax.swing.JLabel();
        jLabelFirst = new javax.swing.JLabel();
        panel_navigation1 = new presentatie.JavaOO_dl3.Panel_navigation();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelDate.setText("Datum:");

        jTextFieldDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDate.setText("2017-07-03");
        jTextFieldDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDateFocusGained(evt);
            }
        });
        jTextFieldDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDateKeyPressed(evt);
            }
        });

        jTextAreaDayProductionInfo.setColumns(20);
        jTextAreaDayProductionInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDayProductionInfo);

        jLabelNext.setIcon(new ImageIcon("images/next.PNG"));
        jLabelNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNextMouseClicked(evt);
            }
        });

        jLabelLast.setIcon(new ImageIcon("images/last.PNG"));
        jLabelLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLastMouseClicked(evt);
            }
        });

        jLabelPrevious.setIcon(new ImageIcon("images/previous.PNG"));
        jLabelPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPreviousMouseClicked(evt);
            }
        });

        jLabelFirst.setIcon(new ImageIcon("images/first.PNG"));
        jLabelFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFirstMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_navigation1Layout = new javax.swing.GroupLayout(panel_navigation1);
        panel_navigation1.setLayout(panel_navigation1Layout);
        panel_navigation1Layout.setHorizontalGroup(
            panel_navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        panel_navigation1Layout.setVerticalGroup(
            panel_navigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_navigation1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNext, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLast, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabelDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDate)
                    .addComponent(jLabelFirst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLast, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_navigation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDateFocusGained
        // TODO add your handling code here:
        this.jTextFieldDate.selectAll();
    }//GEN-LAST:event_jTextFieldDateFocusGained

    private void jLabelNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNextMouseClicked
        // TODO add your handling code here:
        if (this.dayProduction.getDate().isBefore(LocalDate.of(2018, 04, 30))) {
            this.dayProduction.setDate(this.dayProduction.getDate().plusDays(1));
            this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jLabelNextMouseClicked

    private void jLabelLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLastMouseClicked
        // TODO add your handling code here:
        this.dayProduction.setDate(LocalDate.of(2018, 04, 30));
        this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
    }//GEN-LAST:event_jLabelLastMouseClicked

    private void jLabelPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPreviousMouseClicked
        // TODO add your handling code here:
        if (this.dayProduction.getDate().isAfter(LocalDate.of(2017, 07, 03))) {
            this.dayProduction.setDate(this.dayProduction.getDate().minusDays(1));
            this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jLabelPreviousMouseClicked

    private void jLabelFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFirstMouseClicked
        // TODO add your handling code here:
        this.dayProduction.setDate(LocalDate.of(2017, 07, 03));
        this.jTextFieldDate.setText(this.dayProduction.getDate().toString());
        this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
        this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
    }//GEN-LAST:event_jLabelFirstMouseClicked

    private void jTextFieldDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dayProduction = this.createAndDisplayDayProduction(this.jTextFieldDate, this.jTextAreaDayProductionInfo);
            this.panel_navigation1.fillMeasurements(this.dayProduction.fillCustomData());
        }
    }//GEN-LAST:event_jTextFieldDateKeyPressed

    /**
     * Makes a temporary DayProduction object based on what the input of the
     * given textField is, and display the information on the given textArea.
     *
     * @param textField textField from which the date is extracted.
     * @param textArea textArea in which the DayProduction toString will be
     * shown.
     * @return a DayProduction object filled with custom data, based on what
     * date was passed in the textField.
     */
    private DayProduction createAndDisplayDayProduction(JTextField textField, JTextArea textArea) {
        DayProduction tempDayProduction = new DayProduction(textField.getText());
        tempDayProduction.setCustomData();
        textArea.setText(tempDayProduction.toString());
        return tempDayProduction;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_navigation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_navigation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelFirst;
    private javax.swing.JLabel jLabelLast;
    private javax.swing.JLabel jLabelNext;
    private javax.swing.JLabel jLabelPrevious;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDayProductionInfo;
    private javax.swing.JTextField jTextFieldDate;
    private presentatie.JavaOO_dl3.Panel_navigation panel_navigation1;
    // End of variables declaration//GEN-END:variables
}
