package presentatie.JavaOO_dl2;

import data.Data_dl2;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import logica.DayPrestation;
import logica.ProductionUnit;

/**
 *
 * @author Olivier PC
 */
public class Axis_1Day extends javax.swing.JPanel {

    private DayPrestation dayPrestation;
    private ArrayList<ProductionUnit> measurements;
    private String[][] unparsedData;
    private int height;
    private int width;

    /**
     * Creates new form Axis_1Day
     */
    public Axis_1Day() {
        initComponents();
        this.dayPrestation = new DayPrestation("2017-12-10");
        this.dayPrestation.parseMeasurements("dl2");
        this.measurements = this.dayPrestation.getMeasurements();
        this.unparsedData = Data_dl2.parseDataDeel2();
        this.setBorder(BorderFactory.createLineBorder(Color.yellow));
        
    }

    @Override
    protected void paintComponent(Graphics g) {
        this.height = this.getHeight();
        this.width = this.getWidth();

        g.setColor(Color.black);
        for (int i = 1; i < this.unparsedData.length; i++) {
            if (this.unparsedData[i].length == 2) {
                g.drawOval(i * 6, this.height - (int) (Double.parseDouble(this.unparsedData[i][1]) * this.height) - 2, 4, 4);
            } else {
                g.drawOval(i * 6, this.height - 2, 4, 4);
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(400, 576));
        setPreferredSize(new java.awt.Dimension(576, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
